try

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,169 +1,115 @@
-#name: build
-#
-#on:
-#  release:
-#    types: [created]
-#  push:
-#
-#jobs:
-#  lint:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v1
-#        with:
-#          submodules: true
-#
-#      - name: Install latest stable
-#        uses: actions-rs/toolchain@v1
-#        with:
-#          toolchain: stable
-#          override: true
-#          components: rustfmt, clippy
-#
-#      - name: Lint with rustfmt
-#        uses: actions-rs/cargo@v1
-#        with:
-#          command: fmt
-#
-#      - name: Lint with clippy
-#        uses: actions-rs/cargo@v1
-#        with:
-#          command: clippy
-#          args: --all-targets --all-features
-#
-#      - name: Test with cargo
-#        uses: actions-rs/cargo@v1.0.1
-#        with:
-#          command: test
-#          toolchain: stable
-#
-#  build:
-#    runs-on: ${{ matrix.os }}
-#    needs: lint
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        python-version: [3.5, 3.6, 3.7, 3.8]
-#        os: [ubuntu-latest, macos-latest, windows-latest]
-#        exclude:
-#          # There is a known issue where Python C extensions
-#          # can not be built on Python 3.5 on Windows.
-#          # https://github.com/actions/virtual-environments/issues/34
-#          # Therefore, ujson can't be compiled and the build would fail.
-#          - os: windows-latest
-#            python-version: 3.5
-#
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v1
-#        with:
-#          submodules: true
-#
-#      - name: Set up Python ${{ matrix.python-version }}
-#        uses: actions/setup-python@v1
-#        with:
-#          python-version: ${{ matrix.python-version }}
-#
-#      - name: Install dependencies
+name: build
+
+on:
+  push:
+    tags:
+      - 'v*'
+
+jobs:
+  check-version:
+    runs-on: ubuntu-latest
+    env:
+      RUST_BACKTRACE: 1
+
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v2
+        with:
+          submodules: true
+
+      - uses: olegtarasov/get-tag@v2
+        id: tag-name
+        with:
+          tagRegex: "v(.*)"
+          tagRegexGroup: 1
+
+#      - id: package-version
 #        run: |
-#          python -m pip install --upgrade pip
-#          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
-#          echo "::add-path::${HOME}/.poetry/bin"
-#          poetry install
-#      - name: Install latest stable
-#        uses: actions-rs/toolchain@v1
-#        with:
-#          toolchain: stable
-#          override: true
+#          sudo npm i -g json
+#          PACKAGE_VERSION=$(json version -f package.json)
+#          echo $PACKAGE_VERSION
+#          echo "::set-output name=package_version::$PACKAGE_VERSION"
 #
-#      - name: Build Python package
-#        run: poetry run maturin develop --release
+#      - name: Fail on version missmatch
+#        run: exit 1
+#        if: ${{ steps.package-version.outputs.package_version != steps.tag-name.outputs.tag }}
 #
-#  rust-publish:
-#    if: startsWith(github.ref, 'refs/tags/')
-#    needs: build
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v1
-#        with:
-#          submodules: true
-#
-#      - uses: actions-rs/toolchain@v1
-#        with:
-#          toolchain: stable
-#          override: true
-#
-##      - name: Publish on crates.io
-##        run: |
-##          cargo login ${{ secrets.CARGO }}
-##          cargo publish
-##  python-publish:
-##    needs: build
-##    runs-on: ${{ matrix.os }}
-##    strategy:
-##      fail-fast: false
-##      matrix:
-##        python-version: [3.5, 3.6, 3.7, 3.8]
-##        os: [ubuntu-latest, macos-latest, windows-latest]
-##        exclude:
-##          # There is a known issue where Python C extensions
-##          # can not be built on Python 3.5 on Windows.
-##          # https://github.com/actions/virtual-environments/issues/34
-##          # Therefore, ujson can't be compiled and the build would fail.
-##          - os: windows-latest
-##            python-version: 3.5
-##    steps:
-##      - uses: actions/checkout@v1
-##        with:
-##          submodules: true
-##
-##      - uses: actions/setup-python@v1
-##        with:
-##          python-version: ${{ matrix.python-version }}
-##
-##      - name: Install latest stable
-##        uses: actions-rs/toolchain@v1
-##        with:
-##          toolchain: stable
-##          override: true
-##
-##      - name: Install dependencies
-##        run: |
-##          python -m pip install --upgrade pip
-##          pip install poetry
-##          poetry install
-##      - name: Build Python package
-##        run: poetry run maturin build --release --no-sdist --strip --interpreter python${{matrix.python_version}}
-##
-##      - name: List wheels
-##        if: matrix.os == 'windows-latest'
-##        run: dir target\wheels\
-##
-##      - name: List wheels
-##        if:  matrix.os != 'windows-latest'
-##        run: find ./target/wheels/
-##
-##      # Note: Windows doesn't support glob
-##      # https://stackoverflow.com/a/52481267/270334
-##      - name: Install wheels
-##        if:  matrix.os == 'windows-latest'
-##        run: pip install --find-links=target\wheels hyperjson
-##
-##      - name: Install wheels
-##        if:  matrix.os != 'windows-latest'
-##        run: pip install target/wheels/hyperjson*.whl
-##
-##      - name: Release
-##        uses: softprops/action-gh-release@v1
-##        if: startsWith(github.ref, 'refs/tags/')
-##        with:
-##          files: target/wheels/hyperjson*.whl
-##        env:
-##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-##
-##      - name: PyPi publish
-##        if: github.event_name == 'release' && github.event.action == 'created'
-##        env:
-##          MATURIN_PASSWORD: ${{ secrets.PYPI }}
-##        run: poetry run maturin publish --username __token__
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ github.ref }}
+          release_name: Release ${{ github.ref }}
+          draft: true
+
+  python-publish:
+    needs: check-version
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: [3.5, 3.6, 3.7, 3.8]
+        os: [ubuntu-latest, macos-latest, windows-latest]
+        exclude:
+          # There is a known issue where Python C extensions
+          # can not be built on Python 3.5 on Windows.
+          # https://github.com/actions/virtual-environments/issues/34
+          # Therefore, ujson can't be compiled and the build would fail.
+          - os: windows-latest
+            python-version: 3.5
+    steps:
+      - uses: actions/checkout@v1
+        with:
+          submodules: true
+
+      - uses: actions/setup-python@v1
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install latest stable
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          override: true
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install poetry
+          poetry install
+
+      - name: Build Python package
+        run: poetry run maturin build --release --no-sdist --strip --interpreter python${{matrix.python_version}}
+
+      - name: List wheels
+        if: matrix.os == 'windows-latest'
+        run: dir target\wheels\
+
+      - name: List wheels
+        if:  matrix.os != 'windows-latest'
+        run: find ./target/wheels/
+
+      # Note: Windows doesn't support glob
+      # https://stackoverflow.com/a/52481267/270334
+      - name: Install wheels
+        if:  matrix.os == 'windows-latest'
+        run: pip install --find-links=target\wheels hyperjson
+
+      - name: Install wheels
+        if:  matrix.os != 'windows-latest'
+        run: pip install target/wheels/hyperjson*.whl
+
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        with:
+          files: target/wheels/hyperjson*.whl
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+#      - name: PyPi publish
+#        if: github.event_name == 'release' && github.event.action == 'created'
+#        env:
+#          MATURIN_PASSWORD: ${{ secrets.PYPI }}
+#        run: poetry run maturin publish --username __token__
